# Generated by Django 3.1.1 on 2020-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfasthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppdernavimages',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
