# Generated by Django 3.1.1 on 2020-09-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfasthome', '0002_auto_20200922_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppdernavimages',
            name='price',
            field=models.IntegerField(),
        ),
    ]
