# Generated by Django 3.1.1 on 2021-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfasthome', '0003_auto_20200922_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailId', models.CharField(max_length=50)),
                ('commentUser', models.CharField(max_length=500)),
            ],
        ),
    ]
